<a href="https://colab.research.google.com/github/setthawut8/ai/blob/main/%5BLoad_%26_Predict%5D_from_the_saved_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Build Functions for using these loaded model
Inspirations as follows:
- https://machinelearningmastery.com/save-load-keras-deep-learning-models/
- https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/distribute/save_and_load.ipynb#scrollTo=jFcuzsI94bNA


In [1]:
!gdown --id :) #test_data

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1Cq3FttnnzZa-RK7vlu94bJTRj8YD6vA5
To: /content/test_translated banking data.csv
100% 18.7M/18.7M [00:00<00:00, 245MB/s]


In [2]:
import pandas as pd
test = pd.read_csv('/content/test_translated banking data.csv')

##TH2EN_CNN (2 functions)

In [3]:
!gdown --id 1XIUJkhLgjLxbei0QaA0RkPxTtNB6NZiG #model
!gdown --id 1McFf6NPsxlL0g0XmXF9-J4yItudW2OIS #tokenizer

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1XIUJkhLgjLxbei0QaA0RkPxTtNB6NZiG
To: /content/TH2EN_CNN.h5
100% 154M/154M [00:00<00:00, 181MB/s]
/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1McFf6NPsxlL0g0XmXF9-J4yItudW2OIS
To: /content/tokenizer.pickle
100% 460k/460k [00:00<00:00, 74.6MB/s]


In [20]:
sample_test_x = test['translated'][:10]

In [21]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

def text_to_vectors(pickle_path, docs, max_length_of_words):
  with open(pickle_path, 'rb') as handle:
    tokenizer = pickle.load(handle)
  encoded_docs = tokenizer.texts_to_sequences(docs)
  padded_docs = pad_sequences(encoded_docs, maxlen=max_length_of_words, padding='post')
  vocab_size = len(tokenizer.word_index) + 1
  return padded_docs, vocab_size

In [22]:
import pickle
import numpy as np
from keras.utils.np_utils import to_categorical

X, vocab_size = text_to_vectors('/content/tokenizer.pickle', sample_test_x, 190)

In [23]:
import tensorflow as tf
def TH2EN_CNN_prediction(h5_path, padded_docs):
  #Load the model: https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/keras/save_and_load.ipynb#scrollTo=SkGwf-50zLNn
  # Recreate the exact same model, including its weights and the optimizer
  new_model = tf.keras.models.load_model(h5_path)
  # Show the model architecture
  y_pred = new_model.predict(padded_docs)
  rounded_labels_ypred = np.argmax(y_pred, axis=1)+1
  return rounded_labels_ypred

In [24]:
TH2EN_CNN_prediction('/content/TH2EN_CNN.h5', X)

array([ 8, 12,  7, 13,  8,  8,  7, 13,  7,  8])

##TH2EN_GRU (2 functions)

In [9]:
!gdown --id 1UNfJZq3ehiHO3MFnyYmI-o1_fLvoUnAx #model
!gdown --id 1McFf6NPsxlL0g0XmXF9-J4yItudW2OIS #tokenizer

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1UNfJZq3ehiHO3MFnyYmI-o1_fLvoUnAx
To: /content/TH2EN_GRU.h5
100% 166M/166M [00:02<00:00, 59.9MB/s]
/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1McFf6NPsxlL0g0XmXF9-J4yItudW2OIS
To: /content/tokenizer.pickle
100% 460k/460k [00:00<00:00, 127MB/s]


In [25]:
sample_test_x = test['translated'][:10]

In [26]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

def text_to_vectors(pickle_path, docs, max_length_of_words):
  with open(pickle_path, 'rb') as handle:
    tokenizer = pickle.load(handle)
  encoded_docs = tokenizer.texts_to_sequences(docs)
  padded_docs = pad_sequences(encoded_docs, maxlen=max_length_of_words, padding='post')
  vocab_size = len(tokenizer.word_index) + 1
  return padded_docs, vocab_size

In [27]:
import pickle
import numpy as np
from keras.utils.np_utils import to_categorical

X, vocab_size = text_to_vectors('/content/tokenizer.pickle', sample_test_x, 190)

In [28]:
import tensorflow as tf
def TH2EN_GRU_prediction(h5_path, padded_docs):
  #Load the model: https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/keras/save_and_load.ipynb#scrollTo=SkGwf-50zLNn
  # Recreate the exact same model, including its weights and the optimizer
  new_model = tf.keras.models.load_model(h5_path)
  # Show the model architecture
  y_pred = new_model.predict(padded_docs)
  rounded_labels_ypred = np.argmax(y_pred, axis=1)+1
  return rounded_labels_ypred

In [29]:
TH2EN_GRU_prediction('/content/TH2EN_GRU.h5', X)

array([ 8, 12,  7,  4,  8,  8,  7,  8,  7,  8])

##TH2EN_CNN_and_GRU (1 Function)

In [15]:
!gdown --id 1XIUJkhLgjLxbei0QaA0RkPxTtNB6NZiG #model
!gdown --id 1UNfJZq3ehiHO3MFnyYmI-o1_fLvoUnAx #model
!gdown --id 1McFf6NPsxlL0g0XmXF9-J4yItudW2OIS #tokenizer

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1XIUJkhLgjLxbei0QaA0RkPxTtNB6NZiG
To: /content/TH2EN_CNN.h5
100% 154M/154M [00:00<00:00, 343MB/s]
/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1UNfJZq3ehiHO3MFnyYmI-o1_fLvoUnAx
To: /content/TH2EN_GRU.h5
100% 166M/166M [00:02<00:00, 64.9MB/s]
/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https:

In [16]:
sample_test_x = test['translated'][:10]

In [17]:
import pickle
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.sequence import pad_sequences

def text_to_vectors_and_prediction(pickle_path, docs, max_length_of_words, h5_path):
  with open(pickle_path, 'rb') as handle:
    tokenizer = pickle.load(handle)
  encoded_docs = tokenizer.texts_to_sequences(docs)
  padded_docs = pad_sequences(encoded_docs, maxlen=max_length_of_words, padding='post')
  vocab_size = len(tokenizer.word_index) + 1

  #Load the model: https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/keras/save_and_load.ipynb#scrollTo=SkGwf-50zLNn
  # Recreate the exact same model, including its weights and the optimizer
  new_model = tf.keras.models.load_model(h5_path)
  # Show the model architecture
  y_pred = new_model.predict(padded_docs)
  rounded_labels_ypred = np.argmax(y_pred, axis=1)+1
  return rounded_labels_ypred

In [18]:
#CNN
text_to_vectors_and_prediction('/content/tokenizer.pickle', sample_test_x, 190, '/content/TH2EN_CNN.h5')

array([ 8, 12,  7, 13,  8,  8,  7, 13,  7,  8])

In [19]:
#GRU
text_to_vectors_and_prediction('/content/tokenizer.pickle', sample_test_x, 190, '/content/TH2EN_GRU.h5')

array([ 8, 12,  7,  4,  8,  8,  7,  8,  7,  8])